version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - tis-network
networks:
  tis-network:
    driver: bridge
