services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - tis-network
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: tistracker_db
      POSTGRES_USER: tistracker
      POSTGRES_PASSWORD: FKplu4jIG4ivj6k
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    networks:
      - tis-network
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  tis-network:
    driver: bridge
volumes:
  pgdata: